### ISSUE TITLE
Camera module

### ISSUE THREAD

**Issue by tania-19** [GAVLab/ros-hab-dcs#30]
Hi!, i am trying to use the raspberry pi camera module V2, i have raspberry pi 4B and ros noetic.

I followed the steps from Set Up Cameras, but when i write rqt_image_view, it seems i cant connect to my camera:
![image](https://user-images.githubusercontent.com/65095904/110992422-a8f43400-8354-11eb-8c89-bbb534e9ba47.png 
thanks

**Comment by mcberry23** [comment]
I am not currently using a raspberry pi camera module but I am having some issues with setting this up on a new Pi 4B 4GB instead of the 2GB RAM version this project was originally developed on.  I believe this is an issue with the raspicam_node not currently being compatible with ARM64: https://github.com/UbiquityRobotics/raspicam_node/issues/110   Which OS are you using?

**Comment by tania-19** [comment]
Hi! I end up using the newest Ubiquity Robotics Image [here](https://downloads.ubiquityrobotics.com/pi.html) the camera module works fine now, but i haven't try this project because it was developed on ros noetic and ubuntu mate 20.04 and now i have ros kinetic.
